#!/bin/sh

psql molior <<EOF

CREATE TABLE authtoken (
    id integer NOT NULL,
    token character varying,
    description character varying,
    role role_enum,
    project_id integer REFERENCES project(id)
);
ALTER TABLE authtoken OWNER TO molior;

ALTER TABLE ONLY authtoken ADD CONSTRAINT authtoken_pkey PRIMARY KEY (id);

CREATE SEQUENCE authtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER TABLE authtoken_id_seq OWNER TO molior;
ALTER SEQUENCE authtoken_id_seq OWNED BY authtoken.id;
ALTER TABLE ONLY authtoken ALTER COLUMN id SET DEFAULT nextval('authtoken_id_seq'::regclass);
EOF
